# // TODO: Implementar el docker-compose
version: '3.8'

services:
  libreria:
    build: .
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - libreria-data:/data

volumes:
  libreria-data:
